sudo: false
language: node_js
node_js:
  - 13
cache: npm
branches:
  only:
    - hexo-source # store source code of hexo in hexo-source branch
script:
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  # added
  target_branch: master # generate static files to master
  on:
    all_branches: true
    branch: hexo-source # source code of hexo
  local-dir: public